### PR TITLE
Add `ignore_application_differences` to `argocd_application_set` resource

### LINKED ISSUE #352: Add ignoreApplicationDifferences to applicationset resource
### Description
ArgoCD 2.9.0 introduced new concept : [ignoreApplicationDifferences ](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Controlling-Resource-Modification/#ignore-certain-changes-to-applications)
Can you add this attribute to application_set resource

### References
ignoreApplicationDifferences  in ArgoCD docs : https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Controlling-Resource-Modification/#ignore-certain-changes-to-applications

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by dtrouillet**
Fixes #352 

This PR adds support for the ignoreApplicationDifferences parameter in the ApplicationSet resources.
This PR Upgrade ArgoCD dependencies to 2.9.3

### CODE REVIEW

**Comment by dtrouillet** [comment]
Good morning @oboukili,

The pull request also updates ArgoCD to 2.9.3. A test is in error because the behavior of ArgoCD changes, empty blocks such as valuesFiles and syncPolicy of Applications are automatically deleted by ArgoCD. It is therefore necessary, in my opinion, not to create these blocks when they are empty in the Terraform

**Comment by dtrouillet** [comment]
@onematchfox , @oboukili , Can you help me please on this pr?

**Comment by onematchfox** [comment]
> @onematchfox , @oboukili , Can you help me please on this pr?

Apologies for the slow reply - festive break.... Will try take a look at this in the coming days.

**Comment by dtrouillet** [comment]
re-up

**Comment by dtrouillet** [comment]
not stale

**Comment by dtrouillet** [comment]
Not stale

**Review by onematchfox — APPROVED** [review]
@dtrouillet Thanks so much for your patience! :pray: 

Base changes were great and I have now handled the remaining work needed to handle the changes in newer version of ArgoCD.

**Comment by dtrouillet** [comment]
@onematchfox  no problem !
Awesome, thanks a lot.

**Pull request merged**
