### PR TITLE
feat(application): add cascade parameter

### PR DESCRIPTION
**Pull request by raphink**
Signed-off-by: Raphaël Pinson <raphael.pinson@camptocamp.com>

### CODE REVIEW

**Comment by mcanevet** [comment]
@oboukili I don't know why the tests fails, but I used this patch and it works fine for me.

**Comment by oboukili** [comment]
There seems to be an issue with the state version, strange that it happens now given the changes. Could you please look into it? Thanks

**Comment by raphink** [comment]
@oboukili I've tried reproducing locally, but the tests are passing on my machine (and I can't relaunch github actions).

**Comment by raphink** [comment]
https://github.com/gruntwork-io/terratest/issues/1043 and https://github.com/gruntwork-io/terratest/pull/1039 suggest that updating `terraform-json` and `go-cty` might fix this, so it seems unrelated to this PR.

**Comment by raphink** [comment]
Tests still failing on v2.1.3, unrelated to this PR.

**Comment by chap-dr** [comment]
👋 Ive created an issue I think may have something to do with this: https://github.com/oboukili/terraform-provider-argocd/issues/171 Any insights would be appreciated.

**Pull request merged**
