### PR TITLE
Generate provider docs

### PR DESCRIPTION
**Pull request by onematchfox**
I realised when reviewing #224 that some of the provider docs are a bit outdated these days, as the updates occasionally get missed when reviewing PRs. This PR attempts to help address the issue by introducing the use of [tfplugindocs](https://github.com/hashicorp/terraform-plugin-docs) (as recommended in #224) to generate provider documentation ensuring that it is easier to keep this in sync (). 

I have also used the opportunity to:
- do some housekeeping on the GitHub actions 
- clean up the `README.md` slightly whilst also explicitly calling out the provider's use case of managing ArgoCD resources (not bootstrapping/install ArgoCD). This has come up in the past (see #126), and whilst there is/never was any confusion in my head around the provider's purpose, I suspect that others may get confused given that the [Flux terraform provider](https://github.com/fluxcd/terraform-provider-flux)

> allows you to install Flux on Kubernetes and configure it to reconcile the cluster state from a Git repository.

Notes:
- unfortunately, `tfplugindocs` is not perfect, which does result in some loss of documentation for computed fields due to https://github.com/hashicorp/terraform-plugin-docs/issues/66. This affects [cluster `info`](https://github.com/oboukili/terraform-provider-argocd/blob/v4.2.0/docs/resources/cluster.md#attribute-reference).
- Branch is currently based on top of #228, so will leave it in draft until that has been reviewed.

### CODE REVIEW

**Comment by onematchfox** [comment]
@oboukili, this one is now ready for your eyes. FYI, in case you had already scanned some of it, the scope did grow a bit from when I initially opened it as I decided to do some cleaning up in the Makefile and GitHub actions whilst I was integrating the docs generation there.

**Comment by onematchfox** [comment]
@oboukili when you get the chance, please can you take a look at this?

**Comment by onematchfox** [comment]
@oboukili still waiting on you for this one please

**Comment by onematchfox** [comment]
@MrLuje any chance you might be able to review these changes?

**Comment by MrLuje** [comment]
> @MrLuje any chance you might be able to review these changes?

Sure, I'll have a look

**Review by MrLuje — APPROVED** [review]
LGTM, I even learned a new argocd feature will reading the docs :)

**Comment by onematchfox** [comment]
Thanks for the review @MrLuje. Much appreciated!

**Pull request merged**
