### PR TITLE
Add option to pass Client Certificate and Key

### PR DESCRIPTION
**Pull request by marcelobartsch**
This PR add the parameters to pass the Client Certificate

```
client_cert_file
client_cert_key
```
this two new parameters are added to the provider.

### CODE REVIEW

**Comment by marcelobartsch** [comment]
@oboukili Seems there is somehing with the tests? as they fail in a part that was not touched by this PR?

**Comment by oboukili** [comment]
Hi yes it's due to another change that was unfortunately merged in the master branch. I will try and fix that by next week.

**Comment by marcelobartsch** [comment]
> @marcelobartsch could you rebase from the master branch and try again?

done! hope it works now! :)

**Comment by marcelobartsch** [comment]
@oboukili seems all checks passes ok finally! hope you can take a look and get this in a new release soon.

**Comment by marcelobartsch** [comment]
@oboukili Hi Oliver, any update on this?

**Review by oboukili — APPROVED** [review]

**Comment by marcelobartsch** [comment]
Thanks a lot!

**Pull request merged**
